**ANN Model**

In [ ]:
#Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

In [ ]:
#Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values    #take only impactful columns for prediction
y = dataset.iloc[:, -1].values      #Exited is the only dependent variable

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])   #Encode the male female independent variables

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
#One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')  #perform one-hot encoding because there is no any auto relationship between the countries
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**Splitting the dataset into the Training set and Test set**

In [ ]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Initializing the ANN
ann = tf.keras.models.Sequential()   #sequence of layers

#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))     #units = number of neurons in the hidden layer

#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))  #sigmoid activation function is useful to predict the probabilities of binary outcome


In [ ]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])       #adam is the best optimizer for SGD

#Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7606
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4620 - accuracy: 0.7907
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4444 - accuracy: 0.8022
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4257 - accuracy: 0.8148
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4389 - accuracy: 0.8086
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4239 - accuracy: 0.8207
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4379 - accuracy: 0.8072
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4260 - accuracy: 0.8167
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4191 - accuracy: 0.8175
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4142 - accura

In [ ]:
#Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   75]
 [ 201  204]]


0.862